services:
  ros2_dev:
    # — Build the image that lives in .devcontainer/Dockerfile ————————
    build:
      context: ..                       # root of the repo
      dockerfile: docker/Dockerfile
    image: robot-ros2-humble        # resulting image name

    container_name: robot_ros2_devcontainer
    stdin_open: true
    tty: true
    command: /bin/bash                  # default shell when you attach
    network_mode: host                  # helps ROS 2 discovery (optional)

    # — Bind‑mount each git sub‑module into the workspace ————————————
    volumes:

      # BASE_SRC
      - ../submodules/base_src:/home/ros/base_ws/src:rw

      # SENSORS_SRC
      - ../submodules/sensors_src:/home/ros/sensors_ws/src:rw

      # TASK_SRC
      - ../submodules/task_src:/home/ros/task_ws/src:rw

      # Bash Scripts
      - ../bash_scripts:/home/ros/bash_scripts:rw

      # Rosbag Storage
      - ../rosbags:/home/ros/rosbags:rw

      # (Optional) keep colcon’s build artefacts outside the container
      - colcon_cache:/home/ros/.colcon

      # enable mount for gui applications
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

    environment:
      - BASE_WS=/home/ros/base_ws
      - SENSORS_WS=/home/ros/sensors_ws
      - TASK_WS=/home/ros/task_ws
      - BASH_SCRIPTS=/home/ros/bash_scripts
      - ROSBAGS_DIR=/home/ros/rosbags
      - DISPLAY=:0
      - QT_X11_NO_MITSHM=1

volumes:
  colcon_cache:




######################################
# Robot_ROS2_Docker.git_template
# ./docker/[Dockerfile;docker-compose.yml]
# ./submodules/base_src/
# ./submodules/sensors_src/
# ./submodules/task_src/
# ./bash_scripts/[bashrc_extensions.sh]
# ./rosbags/


######################################
# Bunker_ROS2_Docker.git

# ./docker/Dockerfile
# ./docker/docker-compose.yml

# ./submodules/base_src/<agilex_ugv_drivers>
# ./submodules/base_src/<agilex_bunker_drivers>

# ./submodules/sensors_src/<mosaic_h_ros2>
# ./submodules/sensors_src/<realsense_sdk>
# ./submodules/sensors_src/<lora_ros2_bridge>

# ./submodules/task_src/<autonomous_navigation_controller>
# ./submodules/task_src/<scheduling_manager>
# ./submodules/task_src/<archeology_msgs>

# ./bash_scripts/docker_functions.sh
# ./bash_scripts/bashrc_extensions.sh

# ./rosbags/rosbag_20240350.bag


